---
apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: web
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: backend-pfc1 #colcar a minha imagem com a minha aplicaçao /// para o banco criar outro deploment, para o banco#
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        resources:
          requests:
            memory: "256Mi" #No teste de de monolito multiplicar pelo valor de pods no caso 250 * 4
            cpu: "250m" #No teste de de monolito multiplicar pelo valor de pods no caso 250 * 4
          limits:
            memory: "512Mi" #No teste de de monolito multiplicar pelo valor de pods no caso 250 * 4 e colocar um pouco a mais 
            cpu: "500m" #No teste de de monolito multiplicar pelo valor de pods no caso 250 * 4 e colocar um pouco a mais 
        readinessProbe:
          httpGet:
           path: /helfcheck
           port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /helfcheck
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10